# vim:fileencoding=utf-8:foldmethod=marker



# : Manager {{{



[mgr]

cwd = { fg = "#83a598" }

# Hovered
hovered         = { fg = "#32302f", bg = "#b8bb26" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#b8bb26", italic = true }
find_position = { fg = "#a89984", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#b8bb26", bg = "#b8bb26" }
marker_copied   = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut      = { fg = "#fb4934", bg = "#fb4934" }

# Tab
tab_active   = { fg = "#32302f", bg = "#32302f" }
tab_inactive = { fg = "#a89984", bg = "#32302f" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#a89984" }

# Highlighting
# syntect_theme = "~/.config/yazi/Gruvbox-Dark.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#32302f", bg = "#32302f" }


# Progress
progress_label  = { fg = "#a89984", bold = true }
progress_normal = { fg = "#32302f", bg = "#32302f" }
progress_error  = { fg = "#fb4934", bg = "#32302f" }

# Permissions
permissions_t = { fg = "#32302f" }
permissions_r = { fg = "#b8bb26" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#b8bb26" }
permissions_s = { fg = "#32302f" }

# : }}}


# : mode {{{

[mode]
normal_main = { fg = "#32302f", bg = "#a89984", bold = true }
normal_alt = { fg = "#32302f", bg = "#a89984", bold = true }

select_main = { fg = "#32302f", bg = "#b8bb26", bold = true }
select_alt = { fg = "#32302f", bg = "#b8bb26", bold = true }

unset_main  = { fg = "#32302f", bg = "#d3869b", bold = true }
unset_alt  = { fg = "#32302f", bg = "#d3869b", bold = true }

# : }}}


# : Input {{{

[input]
border   = { fg = "#a89984" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#32302f" }
active   = { fg = "#fe8019" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#32302f" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#32302f" }
cand            = { fg = "#83a598" }
rest            = { fg = "#a89984" }
desc            = { fg = "#fe8019" }
separator       = "  "
separator_style = { fg = "#32302f" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#fe8019" }
exec    = { fg = "#83a598" }
desc    = { fg = "#a89984" }
hovered = { bg = "#32302f", bold = true }
footer  = { fg = "#32302f", bg = "#a89984" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#83a598" },

    # Videos
    { mime = "video/*", fg = "#b8bb26" },
    { mime = "audio/*", fg = "#b8bb26" },

    # Archives
    { mime = "application/zip",             fg = "#fe8019" },
    { mime = "application/gzip",            fg = "#fe8019" },
    { mime = "application/x-tar",           fg = "#fe8019" },
    { mime = "application/x-bzip",          fg = "#fe8019" },
    { mime = "application/x-bzip2",         fg = "#fe8019" },
    { mime = "application/x-7z-compressed", fg = "#fe8019" },
    { mime = "application/x-rar",           fg = "#fe8019" },

    # Fallback
    { name = "*", fg = "#a89984" },
    { name = "*/", fg = "#83a598" }
]

# : }}}

